NAME = "vents"
VERSION = "0.4.5"
DESC = "Open source connections, integrations, alerting, and notification library."
URL = "https://github.com/mmourafiq/vents"
AUTHOR = "Mourad Mourafiq"
EMAIL = "mourad.mourafiq@gmail.com"
LICENSE = "Apache 2.0"
